### ISSUE TITLE
Not working properly in components

### ISSUE THREAD

**Issue by KamiKillertO** [ember-infinity/ember-infinity#302]
It's seem that `ember-infinity` des not work properly in components. It never fetch the next page even if the loader is visible.

This is what happen : 
![kapture 2018-07-04 at 10 43 59](https://user-images.githubusercontent.com/9579729/42266780-a5f45b2e-7f77-11e8-8a15-d88deb8f3297.gif)

This is what happen when `ember-infinity` is used in a route :
![kapture 2018-07-04 at 10 42 54](https://user-images.githubusercontent.com/9579729/42266847-d022258e-7f77-11e8-88df-e643de96ae85.gif)

I have create a project which reproduce this issue https://github.com/KamiKillertO/ember-infinity-tests

**Comment by snewcomer** [comment]
@KamiKillertO Awesome reproduction and thanks a ton for the work you put into this issue 🙏 

I'm thinking the lines below is the root of our issue.  Since you are rendering before the promise has resolved (i.e. no route model hook), "content" is undefined on the Array/Promise Proxy.  I think this is a legitimate bug you found.  This probably worked before with rAF but with [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), it only fires once and doesn't keep checking in a loop.  

Temporary work around is to render the component after the fetch has resolved (async/await).  Let's think about a potential solution and see if we can figure out something by the end of the week. 🤝 

https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L121
https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L74

**Comment by KamiKillertO** [comment]
I've just make a quick test and updating the component like this solve the issue

```
  init() {
    this._super(...arguments);
    setTimeout(() => this.set('stores', this.get('infinity').model('store', { perPage: 5 })), 1000);
  }
```

This is obviously not ideal ^^, but it works 😄

**Comment by KamiKillertO** [comment]
I found a better fix, you just need to update your template like this

```hbs
<ul id="infinite-list">
  {{#if stores}}
    {{#each stores as |store|}}
      <li class="infinite__item">{{store.name}}</li>
    {{/each}}
    {{infinity-loader infinityModel=stores}}
  {{else}}
    <span>Loading Infinite Model...</span>
  {{/if}}
</ul>
```

**Comment by snewcomer** [comment]
@KamiKillertO I tried out #303 with your repro and works great!  Lmk if you have time to review that PR and I'll get it in today!

**Comment by KamiKillertO** [comment]
😮 you're so fast 😆. I'll have a look with pleasure
