### ISSUE TITLE
How I can recognize if model in loading mode

### ISSUE THREAD

**Issue by zion03** [ember-infinity/ember-infinity#350]
What is the best way to recognize if model in loading mode like ember `isLoaded`. I need disable some components during `infinity` model is loading.
For example:
```
{{other-component isLoaded=model.products/*loading mode here*/}}
{{p-list products=model.products}}
{{infinity-loader infinityModel=model.products}}
```

**Comment by snewcomer** [comment]
@zion03 We could perhaps make [`_loadingMore`](https://github.com/ember-infinity/ember-infinity/blob/master/addon/services/infinity.js#L314) public.  If your not using ember-concurrency that is.  If so, I think there is some good declarative patterns.  Would happily accept a PR.  Otherwise I will find time over the next few weeks!

https://github.com/ember-infinity/ember-infinity#use-ember-infinity-with-button

**Comment by snewcomer** [comment]
Added `isLoaded` property on the `InfinityModel`.  Lmk if that helps!
