### ISSUE TITLE
Manually add item to infinity.model

### ISSUE THREAD

**Issue by Redsandro** [ember-infinity/ember-infinity#383]
I have a page that's polling the server for new items. They will be prepended to the list and marked as "new". 

Now that I replaced my model with `ember-infinity`, I can't figure out how to do this (or if it's possible).

Can I manipulate the `infinity-model` and prepend an item?

Cursor-based pagination for older items when scrolling down will continue to work fine.

**Comment by snewcomer** [comment]
Do any of these methods help? https://github.com/ember-infinity/ember-infinity#service-methods

If you have any code examples, we could probably solve this with existing methods or improve the API here.

**Comment by LuisAverhoff** [comment]
@snewcomer I have similar situation to @Redsandro. I have a list of processes that I'm infinitely scrolling and at the top of the list there is a button that creates a new process by making an api call to the server. At the moment, I'm force to refresh the current route so that ember infinity can load up the new item that was created on the server side. Can you suggest to me any other alternatives? The only other thing I can think is doing 'model.pushObject(process)' where `model` is the `model` returned in the `model` hook using `this.infinity.model` and process is the object that was returned from gthe  api call. I don't know if this would cause problems later when it comes to fetching new process on the server side. Thanks for your time man.

**Comment by LuisAverhoff** [comment]
I saw that you had a section for cursor based pagination that deals with duplicated items based on an id and a timestamp. Based on what I said, do you think that is what I should go for?

**Comment by Redsandro** [comment]
@snewcomer I'd like to try `pushObjects` or `unshiftObjects`, but they are not documented further than [this](https://github.com/ember-infinity/ember-infinity#service-methods). Is there API documentation on them?

**Comment by snewcomer** [comment]
@redsandro yep! https://api.emberjs.com/ember/3.12/classes/MutableArray/methods/pushObjects?anchor=pushObjects

**Comment by Redsandro** [comment]
Oh! It's an Ember-native method!

This makes me wonder if there is a way to keep a list of links to objects in the model, and when ember-infinity is ~~loaded~~ started because of a history event, automatically load those objects in stead of the default first page.

It would be a good start towards:
* https://github.com/ember-infinity/ember-infinity/issues/384
* https://github.com/ember-infinity/ember-infinity/issues/146

**Comment by snewcomer** [comment]
Does `startingPage` help?  

https://github.com/ember-infinity/ember-infinity#static-parameters

**Comment by Redsandro** [comment]
I think unshift would work for prepending. I have not tried it yet because I went another way, but this specific issue is closed. For now. :)
